{{- $ns := .Values.global.namespace }}
{{- $irsa := .Values.irsa }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-user-service
  namespace: {{ $ns }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $irsa.userServiceRoleArn | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-appointment-service
  namespace: {{ $ns }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $irsa.appointmentServiceRoleArn | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-health-service
  namespace: {{ $ns }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $irsa.healthServiceRoleArn | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-document-service
  namespace: {{ $ns }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $irsa.documentServiceRoleArn | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-rag-service
  namespace: {{ $ns }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $irsa.ragServiceRoleArn | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-rag-worker
  namespace: {{ $ns }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $irsa.ragWorkerRoleArn | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-frontend
  namespace: {{ $ns }}
