# Prod environment overrides — updated by CD pipeline (after manual approval)
global:
  imageRegistry: "371454942267.dkr.ecr.us-east-1.amazonaws.com"
  imageTag: "sha-8b9688d"
  awsRegion: "us-east-1"
  awsAccountId: "371454942267"
  namespace: "arogya-prod"

s3:
  bucketName: "arogya-prod-documents-371454942267"

services:
  user-service:
    replicas: 2
  appointment-service:
    replicas: 2
  health-service:
    replicas: 2
  document-service:
    replicas: 2
  rag-service:
    replicas: 2
  frontend:
    replicas: 2

ragWorker:
  sqsQueueUrl: "https://sqs.us-east-1.amazonaws.com/371454942267/arogya-prod-rag-processing"

appointmentService:
  sqsQueueUrl: "https://sqs.us-east-1.amazonaws.com/371454942267/arogya-prod-appointment-events"

irsa:
  userServiceRoleArn: "arn:aws:iam::371454942267:role/arogya-prod-sa-user-service"
  appointmentServiceRoleArn: "arn:aws:iam::371454942267:role/arogya-prod-sa-appointment-service"
  healthServiceRoleArn: "arn:aws:iam::371454942267:role/arogya-prod-sa-health-service"
  documentServiceRoleArn: "arn:aws:iam::371454942267:role/arogya-prod-sa-document-service"
  ragServiceRoleArn: "arn:aws:iam::371454942267:role/arogya-prod-sa-rag-service"
  ragWorkerRoleArn: "arn:aws:iam::371454942267:role/arogya-prod-sa-rag-worker"
  kedaRoleArn: "arn:aws:iam::371454942267:role/arogya-prod-sa-keda"
